version: '3.8'

services:
  backend:
    image: ghcr.io/your-github-username/qrlinkr-backend:latest # <-- IMPORTANT: Replace with your GitHub username
    container_name: qrlinkr-backend-prod
    restart: unless-stopped
    networks:
      - qrlinkr-net
    environment:
      - DATABASE_URL=${DATABASE_URL} # This will be loaded from a .env file on the NAS
      - API_BASE_URL=${API_BASE_URL}
    depends_on:
      - db

  frontend:
    image: ghcr.io/your-github-username/qrlinkr-frontend:latest # <-- IMPORTANT: Replace with your GitHub username
    container_name: qrlinkr-frontend-prod
    restart: unless-stopped
    networks:
      - qrlinkr-net
    ports:
      - '3000:3000' # Expose frontend on port 3000
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: qrlinkr-db-prod
    restart: unless-stopped
    networks:
      - qrlinkr-net
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  qrlinkr-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
