services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    container_name: qrlinkr-db-prod-hostnet
    restart: unless-stopped
    network_mode: host
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: 
      - postgres
      - -p
      - "5433"  # Use different port to avoid conflicts
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5433',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Backend API Service (Fastify) - Pull from GHCR
  backend:
    image: ghcr.io/asjadaugust/qrlinkr/backend:latest
    container_name: qrlinkr-backend-prod-hostnet
    restart: unless-stopped
    network_mode: host
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5433/${POSTGRES_DB}
      - PORT=3001
      - NODE_ENV=production
      - HOST=0.0.0.0
      # Prisma configuration to avoid binary downloads
      - PRISMA_CLI_BINARY_TARGETS=debian-openssl-3.0.x
      - PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=1
      - PRISMA_DISABLE_WARNINGS=true
      # Additional network debugging
      - PGCONNECT_TIMEOUT=10
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider http://localhost:3001/health || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s

  # Frontend Web Application (Next.js) - Pull from GHCR
  frontend:
    image: ghcr.io/asjadaugust/qrlinkr/frontend:latest
    container_name: qrlinkr-frontend-prod-hostnet
    restart: unless-stopped
    network_mode: host
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${API_BASE_URL}
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

volumes:
  postgres_data:
