services:
  # PostgreSQL Database Service
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-qrlinkr}
      POSTGRES_USER: ${POSTGRES_USER:-qrlinkr}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qrlinkr123}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qrlinkr-net

  # Backend API Service (Fastify)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-qrlinkr}:${POSTGRES_PASSWORD:-qrlinkr123}@db:5432/${POSTGRES_DB:-qrlinkr}
      - PORT=3001
      - NODE_ENV=development
    ports:
      - '3001:3001'
    networks:
      - qrlinkr-net

  # Frontend Web Application (Next.js)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: always
    depends_on:
      - backend
    environment:
      # Frontend API configuration - using host-mapped URL for browser access
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3001
    ports:
      - '3000:3000'
    networks:
      - qrlinkr-net

volumes:
  postgres_data:
    driver: local

networks:
  qrlinkr-net:
    driver: bridge
